name: Download Decrypted IPA

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Decrypted IPA
        uses: itsnebulalol/ios-html5-archiver@main
        with:
          # 依然是 ChatGPT 官方商店链接
          url: "https://apps.apple.com/us/app/chatgpt/id6448311069"
          # 你的 iOSGods 令牌，不需要改
          token: "${{ secrets.SESSION_TOKEN }}"

      - name: Upload IPA to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ChatGPT-Decrypted-IPA
          # 匹配导出的 ipa 文件
          path: "*.ipa"
